module.exports = function(grunt) {
  require("mean-loader").GruntTask.cliche_task(
    grunt,
    "Market",
    [
      "AddAmount",
      "BuyGoodButton",
      "BuyGoodQuantity",
      "BuyGoodFraction",
      "CreateGood",
      "CreateGoodButton",
      "CreateGoodName",
      "CreateGoodPrice",
      "CreateGoodQuantity",
      "ShowAffordableGoods",
      "ShowAllGoods",
      "ShowAllTransactions",
      "ShowBalance",
      "ShowGood",
      "ShowMyGoodsForSale",
      "ShowMyPurchases",
      "ShowTransaction",
      "ShowUnaffordableGoods"
    ]
  );
}
