module.exports = function(grunt) {
  require("mean-loader").GruntTask.cliche_task(
    grunt,
    "Market",
    [
      "AddAmount",
      "BuyGood",
      "BuyGoodAtFractionOfPrice",
      "CreateGood",
      "ShowAffordableGoods",
      "ShowAllGoods",
      "ShowBalance",
      "ShowGood",
      "ShowMyGoodsForSale",
      "ShowMyPurchasedGoods",
      "ShowUnaffordableGoods"
    ]
  );
}
