module.exports = function(grunt) {
  require("mean-loader").GruntTask.cliche_task(
    grunt,
    "Follow",
    [
      "NewFollowerButton",
      "NewPublisherButton",
      "NewMessageButton",
      "ShowNameOfFollower",
      "ShowNameOfPublisher",
      "ShowContentOfMessage",
      "ShowAuthorOfMessage",
      "ShowPublishersByFollower",
      "ShowMessagesByFollower",
      "ShowFollowersByPublisher",
      "ShowMessagesByPublisher",
      "EditNameOfFollower",
      "EditFollowsOfFollower",
      "EditNameOfPublisher",
      "EditContentOfMessage",
      "FollowUnfollow"
    ]
  );
}
