title: rehash
description: assemble web apps from concepts using HTML
# email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
show_downloads: false

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
