title: Déjà Vu
description: assemble web apps from concepts using HTML
# email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deja-vu-platform.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
show_downloads: false

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile

google_site_verification: "f5oum4ohVAl9wkC0jU3W0anZgXtugloaY-QyCp1RRSg"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
